# Generated by Django 3.0.4 on 2020-03-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=60, unique=True)),
                ('file_date', models.DateTimeField(auto_now=True)),
                ('file_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grey.FileClass')),
            ],
        ),
    ]
