# Generated by Django 3.0.4 on 2020-03-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileclass',
            options={'verbose_name_plural': 'FileClasses'},
        ),
        migrations.AlterModelOptions(
            name='fileitem',
            options={'verbose_name_plural': 'FileItems'},
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='file_date',
        ),
    ]
