# Generated by Django 3.0.4 on 2020-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grey', '0002_auto_20200316_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='file_date',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='file_size',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileitem',
            name='file_time',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
