# Generated by Django 3.0.4 on 2020-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grey', '0003_auto_20200322_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file_size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
